version: '3.7'
services:
  web:
    env_file:
      - web-variables.env
    image: infracloudio/csvserver
    ports:
      - "9393:9300"
    volumes:
      - /home/ubuntu/inputdata:/csvserver/inputdata

  prometheus:
    image: prom/prometheus:v2.22.0
    user:  root
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
